#!/bin/bash
echo "###########################################################################"
echo "#  .___        __         .__  .__  .____________      .__        __      #"
echo "#  |   | _____/  |_  ____ |  | |  | |__\______   \____ |__| _____/  |_    #"
echo "#  |   |/    \   __\/ __ \|  | |  | |  ||     ___/  _ \|  |/    \   __\   #"
echo "#  |   |   |  \  | \  ___/|  |_|  |_|  ||    |  (  <_> )  |   |  \  |     #"
echo "#  |___|___|__/__|  \___| |____|____|__||____|   \____/|__|___|__/__|     #"
echo "# ------------------------------------------------------------------------#"
echo "#                         Authorized access only!                         #"
echo "#  This system is for the exclusive use of employees of IntelliPoint      #"
echo "#  Solutions, LLC. Use of this system is subject to the following:        #"
echo "#  1. Users are accessing a proprietary system, which may contain U.S.    #"
echo "#  Government Controlled Unclassified Information (CUI), 2. Information   #"
echo "#  system usage may be monitored, recorded, and subject to audit,         #"
echo "#  3. Unauthorized use of the information system is prohibited and        #"
echo "#  subject to criminal and civil penalties, and 4. Use of the system      #"
echo "#  indicates consent to monitoring and recording.                         #"
echo "###########################################################################"